# 应用名称
spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
    gateway:
      routes:
        - id: route1
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: route2
          uri: http://www.jd.com
          predicates:
            - Query=url,jd
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/app/product/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: third_route
          uri: lb://mall-third
          predicates:
            - Path=/app/third/**
          filters:
            - RewritePath=/app/third/(?<segment>/?.*), /$\{segment}
        - id: memeber_route
          uri: lb://mall-memeber
          predicates:
            - Path=/app/memeber/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/app/ware/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: yimall_host_route
          uri: lb://mall-product
          predicates:
            - Host=yi.mall.com
        - id: msbmall_host_route3
          uri: lb://mall-search
          predicates:
          - Host=yi.search.com
        - id: app_route
          uri: lb://renren-fast
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /renren-fast/$\{segment}
server:
  port: 8070


